# Generated by Django 4.0.5 on 2022-06-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], default='jismoniy', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('sponsor_summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('spend_summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('moderation', 'Moderation'), ('confirmed', 'Confirmed'), ('relected', 'Rejected')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('student_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], default='bachelor', max_length=8)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('allocated_summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('kontrakt_summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.otm')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorToStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sponsor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.student')),
            ],
        ),
    ]
