# Generated by Django 3.2.4 on 2022-06-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='spend_summa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='allocated_summa',
        ),
    ]
